dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: <gcp project id>
      dataset: stg_olist
      threads: 4
      keyfile: <absolute path to json file>
      timeout_seconds: 300
      priority: interactive
      retries: 1
      location: US
