"""
Olist E-Commerce — Executive Analytics Dashboard
=================================================
Reads from local Parquet files generated by generate_parquet.py.

Run:
  python presentation/generate_parquet.py   # once, to build data files
  streamlit run presentation/dashboard.py
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import NamedTuple

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st


class FilterState(NamedTuple):
    date_from:  datetime.date | None
    date_to:    datetime.date | None
    states:     tuple[str, ...]   # empty tuple = all states
    regions:    tuple[str, ...]   # empty tuple = all regions
    categories: tuple[str, ...]   # empty tuple = all categories


# ── Design tokens ─────────────────────────────────────────────────────────────
PAL = {
    "blue":   "#3b82f6",
    "green":  "#22c55e",
    "amber":  "#f59e0b",
    "red":    "#ef4444",
    "teal":   "#14b8a6",
    "purple": "#a855f7",
    "pink":   "#ec4899",
    "indigo": "#6366f1",
}
SEQ = list(PAL.values())
BG   = "rgba(0,0,0,0)"
GRID = "rgba(255,255,255,0.06)"
FONT = "#e2e8f0"
MUTED = "#94a3b8"


def _layout(title: str = "", height: int = 380) -> dict:
    return dict(
        title=dict(text=title, font=dict(color=FONT, size=13)),
        paper_bgcolor=BG,
        plot_bgcolor=BG,
        font=dict(color=FONT, family="system-ui, -apple-system, sans-serif", size=12),
        xaxis=dict(gridcolor=GRID, zeroline=False, showline=False, tickfont=dict(color=MUTED)),
        yaxis=dict(gridcolor=GRID, zeroline=False, showline=False, tickfont=dict(color=MUTED)),
        height=height,
        margin=dict(l=0, r=10, t=40, b=0),
        legend=dict(bgcolor=BG, font=dict(size=11, color=FONT)),
        hoverlabel=dict(bgcolor="#1e293b", font_color=FONT),
    )


# ── Load parquet data (cached for session lifetime) ───────────────────────────
@st.cache_resource
def _load_data() -> dict[str, pd.DataFrame]:
    data_dir = Path(__file__).parent / "data"
    return {
        "orders":              pd.read_parquet(data_dir / "fct_orders.parquet"),
        "order_items":         pd.read_parquet(data_dir / "fct_order_items.parquet"),
        "customers":           pd.read_parquet(data_dir / "dim_customers.parquet"),
        "products":            pd.read_parquet(data_dir / "dim_products.parquet"),
        "sellers":             pd.read_parquet(data_dir / "dim_sellers.parquet"),
        "geography":           pd.read_parquet(data_dir / "dim_geography.parquet"),
        "product_categories":  pd.read_parquet(data_dir / "dim_product_category.parquet"),
        "reviews":             pd.read_parquet(data_dir / "fct_product_reviews.parquet"),
        "payments":            pd.read_parquet(data_dir / "order_payments.parquet"),
    }


_DATA              = _load_data()
ORDERS             = _DATA["orders"]
ORDER_ITEMS        = _DATA["order_items"]
CUSTOMERS          = _DATA["customers"]
PRODUCTS           = _DATA["products"]
SELLERS            = _DATA["sellers"]
GEO                = _DATA["geography"]
PRODUCT_CATEGORIES = _DATA["product_categories"]
REVIEWS            = _DATA["reviews"]
PAYMENTS           = _DATA["payments"]


# ── Filter helper ─────────────────────────────────────────────────────────────
def _filtered_orders(
    filters: FilterState,
    *,
    apply_states: bool = True,
    apply_regions: bool = True,
    apply_categories: bool = True,
) -> pd.DataFrame:
    """Return a filtered slice of fct_orders based on FilterState."""
    df = ORDERS
    if filters.date_from:
        df = df[df["order_purchase_timestamp"].dt.date >= filters.date_from]
    if filters.date_to:
        df = df[df["order_purchase_timestamp"].dt.date <= filters.date_to]
    if apply_states and filters.states:
        df = df[df["customer_state"].isin(filters.states)]
    if apply_regions and filters.regions:
        df = df[df["region"].isin(filters.regions)]
    if apply_categories and filters.categories:
        qualifying = set(
            ORDER_ITEMS.loc[
                ORDER_ITEMS["category_name_english"].isin(filters.categories),
                "order_id",
            ].unique()
        )
        df = df[df["order_id"].isin(qualifying)]
    return df


# ── Query helpers (all cached 1 h) ────────────────────────────────────────────

@st.cache_data(ttl=3600)
def q_overview_kpis(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    fi = ORDER_ITEMS[["order_id", "price", "freight_value"]]
    merged = fo.merge(fi, on="order_id", how="inner")
    merged["item_value"] = merged["price"] + merged["freight_value"]

    order_vals  = merged.groupby("order_id")["item_value"].sum()
    gmv         = order_vals.sum()
    total_orders = len(order_vals)
    aov         = order_vals.mean()

    delivered = fo[
        (fo["order_status"] == "delivered") & fo["order_delivered_customer_date"].notna()
    ]
    if delivered.empty:
        avg_days = float("nan")
        on_time_rate = float("nan")
    else:
        avg_days = (
            delivered["order_delivered_customer_date"] - delivered["order_purchase_timestamp"]
        ).dt.days.mean()
        on_time_rate = (
            delivered["order_delivered_customer_date"] <= delivered["order_estimated_delivery_date"]
        ).mean()

    return pd.DataFrame([{
        "gmv": gmv, "total_orders": total_orders, "aov": aov,
        "delivered": len(delivered), "avg_days": avg_days, "on_time_rate": on_time_rate,
    }])


@st.cache_data(ttl=3600)
def q_review_summary(filters: FilterState) -> pd.DataFrame:
    df = REVIEWS[REVIEWS["review_score"].notna()]
    return pd.DataFrame([{
        "avg_score":      df["review_score"].mean(),
        "total_reviews":  len(df),
        "positive_count": (df["review_sentiment"] == "positive").sum(),
        "negative_count": (df["review_sentiment"] == "negative").sum(),
    }])


@st.cache_data(ttl=3600)
def q_monthly_revenue(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    fo = fo[~fo["order_status"].isin(["canceled", "unavailable"])]
    fi = ORDER_ITEMS[["order_id", "price", "freight_value"]]
    merged = fo.merge(fi, on="order_id", how="inner")
    merged["revenue"] = merged["price"] + merged["freight_value"]
    merged["month"]   = merged["order_purchase_timestamp"].dt.to_period("M").astype(str)

    return (
        merged.groupby("month")
        .agg(revenue=("revenue", "sum"), orders=("order_id", "nunique"))
        .reset_index()
        .sort_values("month")
    )


@st.cache_data(ttl=3600)
def q_order_status(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    return (
        fo.groupby("order_status").size()
        .reset_index(name="cnt")
        .sort_values("cnt", ascending=False)
    )


@st.cache_data(ttl=3600)
def q_category_revenue(filters: FilterState) -> pd.DataFrame:
    # Only date + category filters (no state/region) — mirrors original BQ query
    fi = ORDER_ITEMS[
        ["order_id", "price", "order_purchase_timestamp",
         "product_category_name", "category_name_english", "category_type"]
    ]
    if filters.date_from:
        fi = fi[fi["order_purchase_timestamp"].dt.date >= filters.date_from]
    if filters.date_to:
        fi = fi[fi["order_purchase_timestamp"].dt.date <= filters.date_to]
    if filters.categories:
        fi = fi[fi["category_name_english"].isin(filters.categories)]

    fi = fi.copy()
    fi["category"] = fi["category_name_english"].fillna(
        fi["product_category_name"].fillna("Unknown")
    )
    fi["category_type"] = fi["category_type"].fillna("Other")

    return (
        fi.groupby(["category", "category_type"])
        .agg(revenue=("price", "sum"), orders=("order_id", "nunique"))
        .reset_index()
        .sort_values("revenue", ascending=False)
        .head(15)
    )


@st.cache_data(ttl=3600)
def q_payment_mix(filters: FilterState) -> pd.DataFrame:
    df = PAYMENTS
    return (
        df.groupby("payment_type")
        .agg(orders=("order_id", "nunique"), total_value=("payment_value", "sum"))
        .reset_index()
        .sort_values("orders", ascending=False)
    )


@st.cache_data(ttl=3600)
def q_rfm(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    fo = fo[fo["order_status"].isin(["delivered", "shipped", "invoiced"])]
    fi = ORDER_ITEMS[["order_id", "price"]]
    merged = fo.merge(fi, on="order_id", how="inner")

    if merged.empty:
        return pd.DataFrame(columns=["segment", "customers"])

    max_date = merged["order_purchase_timestamp"].dt.date.max()

    cust = (
        merged.groupby("customer_unique_id")
        .agg(
            last_order=("order_purchase_timestamp", "max"),
            frequency=("order_id",  "nunique"),
            monetary=("price", "sum"),
        )
        .reset_index()
    )
    cust["recency"] = (max_date - cust["last_order"].dt.date).apply(lambda d: d.days)

    def _segment(row) -> str:
        r, f, m = row["recency"], row["frequency"], row["monetary"]
        if r <= 90  and f >= 3 and m >= 300: return "Champions"
        if r <= 180 and f >= 2:              return "Loyal"
        if r <= 90:                          return "Promising"
        if r <= 365:                         return "At Risk"
        return "Inactive"

    cust["segment"] = cust.apply(_segment, axis=1)
    return (
        cust.groupby("segment")["customer_unique_id"]
        .count()
        .reset_index(name="customers")
        .sort_values("customers", ascending=False)
    )


@st.cache_data(ttl=3600)
def q_customer_state(filters: FilterState) -> pd.DataFrame:
    return (
        CUSTOMERS.groupby("customer_state")["customer_unique_id"]
        .nunique()
        .reset_index(name="customers")
        .sort_values("customers", ascending=False)
        .head(15)
    )


@st.cache_data(ttl=3600)
def q_order_frequency(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    cust_counts = fo.groupby("customer_unique_id")["order_id"].nunique()

    def _bucket(n: int) -> str:
        if n == 1: return "1 order"
        if n == 2: return "2 orders"
        if n == 3: return "3 orders"
        return "4+ orders"

    buckets = cust_counts.map(_bucket).value_counts().reset_index()
    buckets.columns = ["bucket", "customers"]
    return buckets.sort_values("bucket")


@st.cache_data(ttl=3600)
def q_delivery_by_state(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    fo = fo[
        (fo["order_status"] == "delivered")
        & fo["order_delivered_customer_date"].notna()
        & fo["order_purchase_timestamp"].notna()
    ].copy()
    fo["delivery_days"] = (
        fo["order_delivered_customer_date"] - fo["order_purchase_timestamp"]
    ).dt.days
    fo["on_time"] = fo["order_delivered_customer_date"] <= fo["order_estimated_delivery_date"]

    agg = (
        fo.groupby("customer_state")
        .agg(
            avg_days=("delivery_days", "mean"),
            on_time_rate=("on_time", "mean"),
            orders=("order_id", "count"),
        )
        .reset_index()
        .rename(columns={"customer_state": "state"})
    )
    return agg[agg["orders"] >= 10].sort_values("avg_days")


@st.cache_data(ttl=3600)
def q_monthly_ontime(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    fo = fo[
        (fo["order_status"] == "delivered")
        & fo["order_delivered_customer_date"].notna()
        & fo["order_purchase_timestamp"].notna()
    ].copy()
    fo["on_time"] = fo["order_delivered_customer_date"] <= fo["order_estimated_delivery_date"]
    fo["month"]   = fo["order_purchase_timestamp"].dt.to_period("M").astype(str)

    return (
        fo.groupby("month")
        .agg(on_time_rate=("on_time", "mean"))
        .reset_index()
        .sort_values("month")
    )


@st.cache_data(ttl=3600)
def q_review_distribution(filters: FilterState) -> pd.DataFrame:
    df = REVIEWS[REVIEWS["review_score"].notna()]
    return (
        df.groupby("review_score").size()
        .reset_index(name="cnt")
        .sort_values("review_score")
    )


@st.cache_data(ttl=3600)
def q_sentiment_by_category(filters: FilterState) -> pd.DataFrame:
    r = REVIEWS[REVIEWS["review_score"].notna()].copy()

    # Join with orders to get timestamp for date filter
    order_ts = ORDERS[["order_id", "order_purchase_timestamp"]].rename(columns={"order_id": "order_key"})
    r = r.merge(order_ts, on="order_key", how="inner")

    if filters.date_from:
        r = r[r["order_purchase_timestamp"].dt.date >= filters.date_from]
    if filters.date_to:
        r = r[r["order_purchase_timestamp"].dt.date <= filters.date_to]

    # Join with products and categories for category filter
    cat_curr = PRODUCT_CATEGORIES[PRODUCT_CATEGORIES["is_current"]][
        ["category_name", "category_name_english", "category_type"]
    ]
    prod_cat = PRODUCTS[["product_id", "product_category_name"]].merge(
        cat_curr, left_on="product_category_name", right_on="category_name", how="left"
    )
    r = r.merge(prod_cat, left_on="product_key", right_on="product_id", how="left")

    if filters.categories:
        r = r[r["category_name_english"].isin(filters.categories)]

    r["category_type"] = r["category_type"].fillna("Other")

    agg = (
        r.groupby("category_type")
        .agg(
            positive_rate=("review_sentiment", lambda x: (x == "positive").mean()),
            avg_score=("review_score", "mean"),
            cnt=("review_id", "count"),
        )
        .reset_index()
    )
    return (
        agg[agg["cnt"] >= 10]
        .sort_values("positive_rate", ascending=False)
    )


@st.cache_data(ttl=3600)
def q_monthly_rating(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    r  = REVIEWS[REVIEWS["review_score"].notna()].copy()
    r  = r[r["order_key"].isin(fo["order_id"])]

    order_ts = ORDERS[["order_id", "order_purchase_timestamp"]].rename(columns={"order_id": "order_key"})
    r = r.merge(order_ts, on="order_key", how="inner")
    r = r[r["order_purchase_timestamp"].notna()]
    r["month"] = r["order_purchase_timestamp"].dt.to_period("M").astype(str)

    return (
        r.groupby("month")
        .agg(avg_score=("review_score", "mean"), reviews=("review_id", "count"))
        .reset_index()
        .sort_values("month")
    )


@st.cache_data(ttl=3600)
def q_total_products(filters: FilterState) -> int:
    return int(PRODUCTS["product_id"].nunique())


# ── Geography & Logistics queries ──────────────────────────────────────────────

@st.cache_data(ttl=3600)
def q_customer_order_map(filters: FilterState) -> pd.DataFrame:
    fo = _filtered_orders(filters)
    fi = ORDER_ITEMS[["order_id", "price"]]
    merged = fo.merge(fi, on="order_id", how="inner")
    merged = merged.merge(
        GEO[["zip_code_prefix", "latitude", "longitude", "city"]],
        left_on="customer_zip_code", right_on="zip_code_prefix", how="inner",
    )
    merged = merged.dropna(subset=["latitude", "longitude"])

    result = (
        merged.groupby(["latitude", "longitude", "city", "customer_state", "region"])
        .agg(orders=("order_id", "nunique"), revenue=("price", "sum"))
        .reset_index()
        .rename(columns={"latitude": "lat", "longitude": "lng", "customer_state": "state"})
    )
    return result


@st.cache_data(ttl=3600)
def q_seller_map(filters: FilterState) -> pd.DataFrame:
    sellers_geo = SELLERS.merge(
        GEO[["zip_code_prefix", "latitude", "longitude", "city", "state", "region"]],
        left_on="seller_zip_code", right_on="zip_code_prefix", how="inner",
    ).dropna(subset=["latitude", "longitude"])

    if filters.regions:
        sellers_geo = sellers_geo[sellers_geo["region"].isin(filters.regions)]

    return (
        sellers_geo.groupby(["latitude", "longitude", "city", "state", "region"])
        .agg(seller_count=("seller_id", "nunique"))
        .reset_index()
        .rename(columns={"latitude": "lat", "longitude": "lng"})
    )


@st.cache_data(ttl=3600)
def q_regional_performance(filters: FilterState) -> pd.DataFrame:
    # Only date + region filters (no state/category) — mirrors original BQ query
    fo = ORDERS[ORDERS["order_delivered_customer_date"].notna()].copy()

    if filters.date_from:
        fo = fo[fo["order_purchase_timestamp"].dt.date >= filters.date_from]
    if filters.date_to:
        fo = fo[fo["order_purchase_timestamp"].dt.date <= filters.date_to]
    if filters.regions:
        fo = fo[fo["region"].isin(filters.regions)]

    fi = ORDER_ITEMS[["order_id", "price"]]
    merged = fo.merge(fi, on="order_id", how="inner")

    merged["delivery_days"] = (
        merged["order_delivered_customer_date"] - merged["order_purchase_timestamp"]
    ).dt.days

    return (
        merged.groupby("region")
        .agg(
            orders=("order_id", "nunique"),
            revenue=("price", "sum"),
            avg_delivery_days=("delivery_days", "mean"),
        )
        .reset_index()
        .sort_values("revenue", ascending=False)
    )


# ── Filter dimension loaders (cached, no filter args) ─────────────────────────

@st.cache_data(ttl=3600)
def q_filter_date_range() -> pd.DataFrame:
    ts = ORDERS["order_purchase_timestamp"].dropna()
    return pd.DataFrame([{"min_date": ts.min().date(), "max_date": ts.max().date()}])


@st.cache_data(ttl=3600)
def q_filter_states() -> list[str]:
    return sorted(CUSTOMERS["customer_state"].dropna().unique().tolist())


@st.cache_data(ttl=3600)
def q_filter_regions() -> list[str]:
    return sorted(GEO["region"].dropna().unique().tolist())


@st.cache_data(ttl=3600)
def q_filter_categories() -> list[str]:
    cats = (
        PRODUCT_CATEGORIES[PRODUCT_CATEGORIES["is_current"]]["category_name_english"]
        .dropna()
    )
    return sorted(cats.unique().tolist())


# ── Formatters ────────────────────────────────────────────────────────────────
def _brl(v: float) -> str:
    return f"R${v:,.0f}"

def _pct(v: float) -> str:
    return f"{v * 100:.1f}%"

def _num(v: float) -> str:
    return f"{int(v):,}"

def _fmt_cat(s: str) -> str:
    """'bed_bath_table' → 'Bed Bath Table'"""
    return s.replace("_", " ").title()


# ══════════════════════════════════════════════════════════════════════════════
# PAGE SETUP
# ══════════════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="Olist Analytics — Executive Dashboard",
    page_icon="🏭",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
/* Tighten top padding */
.block-container { padding-top: 1.2rem !important; padding-bottom: 0 !important; }

/* Metric cards */
[data-testid="metric-container"] {
    background: #1e293b;
    border: 1px solid rgba(255,255,255,0.08);
    border-radius: 0.75rem;
    padding: 1rem 1.3rem !important;
}
[data-testid="stMetricValue"]  { font-size: 1.75rem !important; font-weight: 700 !important; }
[data-testid="stMetricLabel"]  { font-size: 0.76rem !important; color: #94a3b8 !important;
                                  text-transform: uppercase; letter-spacing: 0.05em; }
[data-testid="stMetricDelta"]  { font-size: 0.8rem !important; }

/* Tab labels */
[data-testid="stTabs"] button[role="tab"] {
    font-weight: 600;
    font-size: 0.88rem;
    letter-spacing: 0.02em;
}
[data-testid="stTabs"] button[role="tab"][aria-selected="true"] {
    color: #3b82f6 !important;
    border-bottom-color: #3b82f6 !important;
}

/* Horizontal rule */
hr { border-color: rgba(255,255,255,0.08) !important; margin: 0.6rem 0 !important; }

/* Sidebar */
[data-testid="stSidebar"] { background: #1e293b !important; border-right: 1px solid rgba(255,255,255,0.06); }
</style>
""", unsafe_allow_html=True)


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🏭 Olist Analytics")
    st.markdown("**Executive Dashboard**")
    st.markdown("---")

    # ── Filters ───────────────────────────────────────────────────────────────
    st.markdown("### Filters")

    _dr     = q_filter_date_range().iloc[0]
    _min_dt = _dr["min_date"]
    _max_dt = _dr["max_date"]

    _col_f, _col_t = st.columns(2)
    _f_date_from = _col_f.date_input(
        "From", value=_min_dt, min_value=_min_dt, max_value=_max_dt, key="filt_date_from"
    )
    _f_date_to = _col_t.date_input(
        "To", value=_max_dt, min_value=_min_dt, max_value=_max_dt, key="filt_date_to"
    )

    if _f_date_from > _f_date_to:
        st.error("'From' date must be ≤ 'To' date.")
        st.stop()

    _f_categories = st.multiselect(
        "Product Category",
        options=q_filter_categories(),
        default=[],
        placeholder="All categories",
        key="filt_categories",
    )
    _f_states = st.multiselect(
        "State",
        options=q_filter_states(),
        default=[],
        placeholder="All states",
        key="filt_states",
    )
    _f_regions = st.multiselect(
        "Region",
        options=q_filter_regions(),
        default=[],
        placeholder="All regions",
        key="filt_regions",
    )

    # Build the active filter state — None for dates at their defaults so that
    # unfiltered queries produce identical results (cache-friendly).
    FILTERS = FilterState(
        date_from=_f_date_from  if _f_date_from != _min_dt else None,
        date_to=_f_date_to      if _f_date_to   != _max_dt else None,
        states=tuple(_f_states),
        regions=tuple(_f_regions),
        categories=tuple(_f_categories),
    )

    st.markdown("---")
    st.markdown("**Data Source**")
    st.markdown("Local Parquet · dbt schema")
    st.markdown("**Dataset Period**")
    st.markdown("Sep 2016 – Oct 2018")
    st.markdown("---")
    st.markdown("**Stack**")
    st.caption("Parquet · dbt · Meltano · Great Expectations")
    st.markdown("---")
    if st.button("🔄 Refresh data", use_container_width=True):
        st.cache_data.clear()
        st.rerun()
    st.caption("Cache TTL: 60 min")


# ── Page header ───────────────────────────────────────────────────────────────
st.markdown(
    "## Olist E-Commerce &nbsp;·&nbsp; Analytics Dashboard",
    unsafe_allow_html=True,
)
st.caption("Brazilian e-commerce platform · Sep 2016 – Oct 2018 · Data via local Parquet star schema")
st.markdown("---")

_active_filter_labels: list[str] = []
if FILTERS.date_from or FILTERS.date_to:
    _df_str = FILTERS.date_from.isoformat() if FILTERS.date_from else str(_min_dt)
    _dt_str = FILTERS.date_to.isoformat()   if FILTERS.date_to   else str(_max_dt)
    _active_filter_labels.append(f"Date: {_df_str} → {_dt_str}")
if FILTERS.states:
    _active_filter_labels.append(f"States: {', '.join(FILTERS.states)}")
if FILTERS.regions:
    _active_filter_labels.append(f"Regions: {', '.join(FILTERS.regions)}")
if FILTERS.categories:
    n = len(FILTERS.categories)
    _active_filter_labels.append(f"Categories: {n} selected")
if _active_filter_labels:
    st.info("Active filters: " + " · ".join(_active_filter_labels), icon="🔍")


# ══════════════════════════════════════════════════════════════════════════════
# TABS
# ══════════════════════════════════════════════════════════════════════════════
TAB_OVERVIEW, TAB_REVENUE, TAB_CUSTOMERS, TAB_OPS, TAB_PRODUCTS, TAB_GEO = st.tabs([
    "📊 Overview",
    "💰 Revenue & Growth",
    "👥 Customer Intelligence",
    "🚚 Operations & Delivery",
    "⭐ Products & Sentiment",
    "🗺️ Geography & Logistics",
])


# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 · OVERVIEW
# ══════════════════════════════════════════════════════════════════════════════
with TAB_OVERVIEW:
    with st.spinner("Loading overview data…"):
        _kpis_df  = q_overview_kpis(FILTERS)
        _score_df = q_review_summary(FILTERS)

    if _kpis_df.empty or pd.isna(_kpis_df.iloc[0]["total_orders"]):
        st.info("No data for the selected filters.")
    else:
        kpis  = _kpis_df.iloc[0]
        score = _score_df.iloc[0]

        # ── KPI row ──────────────────────────────────────────────────────────────
        c1, c2, c3, c4, c5 = st.columns(5)
        c1.metric("Total GMV",          _brl(kpis["gmv"]))
        c2.metric("Total Orders",       _num(kpis["total_orders"]))
        c3.metric("Avg Order Value",    _brl(kpis["aov"]))
        c4.metric("On-Time Delivery",   _pct(kpis["on_time_rate"]))
        c5.metric("Avg Review Score",   f"{score['avg_score']:.2f} / 5 ★")

        st.markdown("---")

        # ── Charts row ───────────────────────────────────────────────────────────
        col_l, col_m, col_r = st.columns([3, 1.4, 1.4])

        with col_l:
            with st.spinner():
                monthly = q_monthly_revenue(FILTERS)
            fig = go.Figure()
            fig.add_trace(go.Scatter(
                x=monthly["month"], y=monthly["revenue"],
                mode="lines+markers",
                name="GMV (R$)",
                line=dict(color=PAL["blue"], width=2.5),
                marker=dict(size=4),
                fill="tozeroy",
                fillcolor="rgba(59,130,246,0.10)",
            ))
            fig.update_layout(**_layout("Monthly GMV (R$) — Sep 2016 to Oct 2018", 320))
            fig.update_yaxes(tickprefix="R$", tickformat=",.0f")
            st.plotly_chart(fig, use_container_width=True)

        with col_m:
            with st.spinner():
                status_df = q_order_status(FILTERS)
            fig = px.pie(
                status_df, values="cnt", names="order_status",
                hole=0.55, color_discrete_sequence=SEQ,
            )
            fig.update_traces(textposition="inside", textinfo="percent+label",
                              textfont_size=10)
            fig.update_layout(**_layout("Order Status", 320))
            st.plotly_chart(fig, use_container_width=True)

        with col_r:
            with st.spinner():
                cat_df = q_category_revenue(FILTERS).head(6)
            cat_df["category"] = cat_df["category"].map(_fmt_cat)
            fig = px.bar(
                cat_df, x="revenue", y="category", orientation="h",
                color_discrete_sequence=[PAL["teal"]],
                labels={"revenue": "Revenue (R$)", "category": ""},
            )
            fig.update_layout(**_layout("Top 6 Categories by Revenue", 320))
            fig.update_xaxes(tickprefix="R$", tickformat=",.0f")
            st.plotly_chart(fig, use_container_width=True)

        # ── Secondary KPI row ────────────────────────────────────────────────────
        st.markdown("---")
        s1, s2, s3, s4 = st.columns(4)
        s1.metric("Avg Delivery Days",  f"{kpis['avg_days']:.1f} days")
        s2.metric("Delivered Orders",   _num(kpis["delivered"]))
        s3.metric("Total Reviews",      _num(score["total_reviews"]))
        s4.metric("Positive Reviews",   _pct(score["positive_count"] / score["total_reviews"]))


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 · REVENUE & GROWTH
# ══════════════════════════════════════════════════════════════════════════════
with TAB_REVENUE:
    with st.spinner("Loading revenue data…"):
        monthly   = q_monthly_revenue(FILTERS)
        cat_df    = q_category_revenue(FILTERS)
        pay_df    = q_payment_mix(FILTERS)
        _kpis_df  = q_overview_kpis(FILTERS)

    if monthly.empty or _kpis_df.empty or pd.isna(_kpis_df.iloc[0]["total_orders"]):
        st.info("No data for the selected filters.")
    else:
        kpis      = _kpis_df.iloc[0]
        cat_df["category"] = cat_df["category"].map(_fmt_cat)
        monthly["mom_growth"] = monthly["revenue"].pct_change() * 100
        peak = monthly.loc[monthly["revenue"].idxmax()]
        best = cat_df.iloc[0]

        # ── KPI row ──────────────────────────────────────────────────────────────
        r1, r2, r3, r4 = st.columns(4)
        r1.metric("Total GMV",         _brl(kpis["gmv"]))
        r2.metric("Peak Month Revenue", _brl(peak["revenue"]), peak["month"])
        r3.metric("MoM Growth (latest)", f"{monthly['mom_growth'].iloc[-1]:.1f}%")
        r4.metric("Top Category",       best["category"], _brl(best["revenue"]))

        st.markdown("---")

        # ── Dual-axis: revenue bars + orders line ─────────────────────────────
        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=monthly["month"], y=monthly["revenue"],
            name="Revenue (R$)",
            marker_color=PAL["blue"],
            opacity=0.82,
            yaxis="y1",
        ))
        fig.add_trace(go.Scatter(
            x=monthly["month"], y=monthly["orders"],
            name="Orders",
            mode="lines+markers",
            line=dict(color=PAL["amber"], width=2.2),
            marker=dict(size=4),
            yaxis="y2",
        ))
        fig.update_layout(**_layout("Monthly Revenue (R$) & Order Volume", 360))
        fig.update_layout(
            yaxis=dict(title="Revenue (R$)", gridcolor=GRID,
                       tickprefix="R$", tickformat=",.0f", tickfont=dict(color=MUTED)),
            yaxis2=dict(title="Orders", overlaying="y", side="right",
                        gridcolor="rgba(0,0,0,0)", tickfont=dict(color=MUTED)),
            barmode="overlay",
            legend=dict(x=0.01, y=0.99, bgcolor=BG),
        )
        st.plotly_chart(fig, use_container_width=True)

        col_cat, col_pay = st.columns([3, 2])

        with col_cat:
            fig = px.bar(
                cat_df.head(12), x="revenue", y="category", orientation="h",
                color="category_type", color_discrete_sequence=SEQ,
                labels={"revenue": "Revenue (R$)", "category": ""},
            )
            fig.update_layout(**_layout("Top 12 Categories by Revenue", 420))
            fig.update_xaxes(tickprefix="R$", tickformat=",.0f")
            st.plotly_chart(fig, use_container_width=True)

        with col_pay:
            LABELS = {
                "credit_card":  "Credit Card",
                "boleto":        "Boleto",
                "voucher":       "Voucher",
                "debit_card":    "Debit Card",
                "not_defined":   "Other",
            }
            pay_df["label"] = pay_df["payment_type"].map(lambda x: LABELS.get(x, x))
            fig = px.pie(
                pay_df, values="orders", names="label",
                hole=0.55, color_discrete_sequence=SEQ,
            )
            fig.update_traces(textposition="inside", textinfo="percent+label",
                              textfont_size=11)
            fig.update_layout(**_layout("Payment Method Mix (by Order Count)", 420))
            st.plotly_chart(fig, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 · CUSTOMER INTELLIGENCE
# ══════════════════════════════════════════════════════════════════════════════
with TAB_CUSTOMERS:
    with st.spinner("Loading customer data…"):
        rfm_df   = q_rfm(FILTERS)
        state_df = q_customer_state(FILTERS)
        freq_df  = q_order_frequency(FILTERS)

    if rfm_df.empty:
        st.info("No data for the selected filters.")
    else:
        total_cust  = int(rfm_df["customers"].sum())
        champions   = int(rfm_df.loc[rfm_df["segment"] == "Champions", "customers"].sum())
        at_risk     = int(rfm_df.loc[rfm_df["segment"] == "At Risk",    "customers"].sum())
        inactive    = int(rfm_df.loc[rfm_df["segment"] == "Inactive",   "customers"].sum())
        active_rate = 1.0 - (inactive / total_cust) if total_cust else 0.0

        # ── KPI row ──────────────────────────────────────────────────────────────
        cx1, cx2, cx3, cx4 = st.columns(4)
        cx1.metric("Total Customers",    _num(total_cust))
        cx2.metric("Champions",          _num(champions),
                   f"{champions / total_cust * 100:.1f}% of base")
        cx3.metric("At-Risk Customers",  _num(at_risk),
                   f"{at_risk / total_cust * 100:.1f}%")
        cx4.metric("Active Customers",   _pct(active_rate))

        st.markdown("---")

        col_a, col_b, col_c = st.columns([1.2, 2, 1])

        with col_a:
            SEG_COLORS = {
                "Champions": PAL["green"],
                "Loyal":     PAL["teal"],
                "Promising": PAL["blue"],
                "At Risk":   PAL["amber"],
                "Inactive":  PAL["red"],
            }
            fig = px.pie(
                rfm_df, values="customers", names="segment",
                hole=0.55,
                color="segment",
                color_discrete_map=SEG_COLORS,
            )
            fig.update_traces(textposition="inside", textinfo="percent+label",
                              textfont_size=10)
            fig.update_layout(**_layout("RFM Customer Segments", 400))
            st.plotly_chart(fig, use_container_width=True)

        with col_b:
            fig = px.bar(
                state_df, x="customer_state", y="customers",
                color="customers",
                color_continuous_scale=["#1e3a8a", PAL["blue"], PAL["teal"]],
                labels={"customer_state": "State (BR)", "customers": "Unique Customers"},
            )
            fig.update_layout(**_layout("Unique Customers by State", 400))
            fig.update_coloraxes(showscale=False)
            st.plotly_chart(fig, use_container_width=True)

        with col_c:
            BUCKET_ORDER = ["1 order", "2 orders", "3 orders", "4+ orders"]
            freq_df["bucket"] = pd.Categorical(
                freq_df["bucket"], categories=BUCKET_ORDER, ordered=True
            )
            freq_df = freq_df.sort_values("bucket")
            fig = px.bar(
                freq_df, x="customers", y="bucket", orientation="h",
                color_discrete_sequence=[PAL["purple"]],
                labels={"customers": "Customers", "bucket": ""},
                text="customers",
            )
            fig.update_traces(texttemplate="%{text:,}", textposition="outside")
            fig.update_layout(**_layout("Purchase Frequency Distribution", 400))
            st.plotly_chart(fig, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 · OPERATIONS & DELIVERY
# ══════════════════════════════════════════════════════════════════════════════
with TAB_OPS:
    with st.spinner("Loading operations data…"):
        del_state  = q_delivery_by_state(FILTERS)
        ontime_df  = q_monthly_ontime(FILTERS)
        status_df  = q_order_status(FILTERS)
        _kpis_df   = q_overview_kpis(FILTERS)

    if _kpis_df.empty or pd.isna(_kpis_df.iloc[0]["on_time_rate"]):
        st.info("No data for the selected filters.")
    else:
        kpis      = _kpis_df.iloc[0]
        total_ord  = int(status_df["cnt"].sum())
        cancelled  = int(
            status_df.loc[status_df["order_status"] == "canceled", "cnt"].sum()
            if "canceled" in status_df["order_status"].values else 0
        )

        # ── KPI row ──────────────────────────────────────────────────────────────
        d1, d2, d3, d4 = st.columns(4)
        d1.metric("On-Time Delivery Rate", _pct(kpis["on_time_rate"]))
        d2.metric("Avg Delivery Days",     f"{kpis['avg_days']:.1f} days")
        d3.metric("Delivered Orders",      _num(kpis["delivered"]))
        d4.metric("Cancellation Rate",     _pct(cancelled / total_ord) if total_ord else "0%")

        st.markdown("---")

        col_x, col_y = st.columns([3, 2])

        with col_x:
            if not del_state.empty:
                ds = del_state.sort_values("avg_days")
                bar_colors = [
                    PAL["green"] if d <= 10
                    else PAL["amber"] if d <= 15
                    else PAL["red"]
                    for d in ds["avg_days"]
                ]
                fig = go.Figure(go.Bar(
                    x=ds["avg_days"],
                    y=ds["state"],
                    orientation="h",
                    marker_color=bar_colors,
                    text=ds["avg_days"].round(1).astype(str) + " days",
                    textposition="outside",
                    textfont=dict(size=11, color=FONT),
                ))
                fig.update_layout(
                    **_layout("Avg Delivery Days by Customer State  🟢 ≤ 10  🟡 ≤ 15  🔴 > 15", 520),
                )
                fig.update_xaxes(title="Days", range=[0, ds["avg_days"].max() * 1.22])
                st.plotly_chart(fig, use_container_width=True)

        with col_y:
            if not ontime_df.empty:
                fig2 = go.Figure(go.Scatter(
                    x=ontime_df["month"],
                    y=ontime_df["on_time_rate"] * 100,
                    mode="lines+markers",
                    line=dict(color=PAL["green"], width=2.5),
                    marker=dict(size=4),
                    fill="tozeroy",
                    fillcolor="rgba(34,197,94,0.10)",
                ))
                fig2.update_layout(**_layout("Monthly On-Time Delivery Rate (%)", 250))
                fig2.update_yaxes(ticksuffix="%", range=[0, 115])
                fig2.add_hline(y=90, line_dash="dot", line_color="rgba(255,255,255,0.25)",
                               annotation_text="90% target", annotation_font_color=MUTED)
                st.plotly_chart(fig2, use_container_width=True)

            if not status_df.empty:
                fig3 = px.pie(
                    status_df, values="cnt", names="order_status",
                    hole=0.55, color_discrete_sequence=SEQ,
                )
                fig3.update_traces(textposition="inside", textinfo="percent+label",
                                   textfont_size=10)
                fig3.update_layout(**_layout("Order Status Breakdown", 260))
                st.plotly_chart(fig3, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 5 · PRODUCTS & SENTIMENT
# ══════════════════════════════════════════════════════════════════════════════
with TAB_PRODUCTS:
    with st.spinner("Loading product & sentiment data…"):
        rev_dist = q_review_distribution(FILTERS)
        sent_df  = q_sentiment_by_category(FILTERS)
        if not sent_df.empty:
            sent_df["category_type"] = sent_df["category_type"].map(_fmt_cat)
        rating_m = q_monthly_rating(FILTERS)
        _score_df = q_review_summary(FILTERS)
        score    = _score_df.iloc[0]
        n_prod   = q_total_products(FILTERS)

    if rev_dist.empty:
        st.info("No data for the selected filters.")
    else:
        positive_rate = (
            rev_dist.loc[rev_dist["review_score"] >= 4, "cnt"].sum()
            / rev_dist["cnt"].sum()
        )

        # ── KPI row ──────────────────────────────────────────────────────────────
        p1, p2, p3, p4 = st.columns(4)
        p1.metric("Total Products",      _num(n_prod))
        p2.metric("Avg Review Score",    f"{score['avg_score']:.2f} / 5 ★")
        p3.metric("Positive Review Rate", _pct(positive_rate))
        p4.metric("Total Reviews",       _num(score["total_reviews"]))

        st.markdown("---")

        col_1, col_2, col_3 = st.columns([1, 2, 1.2])

        with col_1:
            rev_dist["label"] = rev_dist["review_score"].astype(str) + " ★"
            STAR_COLORS = {
                "1 ★": PAL["red"],
                "2 ★": "#f97316",
                "3 ★": PAL["amber"],
                "4 ★": "#84cc16",
                "5 ★": PAL["green"],
            }
            fig = px.bar(
                rev_dist, x="cnt", y="label", orientation="h",
                color="label", color_discrete_map=STAR_COLORS,
                labels={"cnt": "Reviews", "label": "Score"},
                text="cnt",
            )
            fig.update_traces(texttemplate="%{text:,}", textposition="outside")
            fig.update_layout(**_layout("Review Score Distribution", 360))
            fig.update_layout(showlegend=False)
            st.plotly_chart(fig, use_container_width=True)

        with col_2:
            if not sent_df.empty:
                fig2 = px.bar(
                    sent_df,
                    x="positive_rate",
                    y="category_type",
                    orientation="h",
                    color="avg_score",
                    color_continuous_scale=["#ef4444", PAL["amber"], PAL["green"]],
                    range_color=[3.0, 5.0],
                    labels={
                        "positive_rate": "Positive Review Rate",
                        "category_type": "Category",
                        "avg_score": "Avg Score",
                    },
                    text=sent_df["positive_rate"].map(lambda x: f"{x*100:.0f}%"),
                )
                fig2.update_traces(textposition="outside")
                fig2.update_xaxes(tickformat=".0%", range=[0, 1.08])
                fig2.update_layout(**_layout("Positive Review Rate by Category Type", 360))
                fig2.update_coloraxes(
                    colorbar=dict(
                        title=dict(text="Avg ★", font=dict(color=MUTED)),
                        tickfont=dict(color=MUTED),
                        bgcolor=BG,
                    )
                )
                st.plotly_chart(fig2, use_container_width=True)

        with col_3:
            if not rating_m.empty:
                fig3 = go.Figure()
                fig3.add_trace(go.Scatter(
                    x=rating_m["month"],
                    y=rating_m["avg_score"],
                    mode="lines+markers",
                    line=dict(color=PAL["amber"], width=2.5),
                    marker=dict(size=4),
                    fill="tozeroy",
                    fillcolor="rgba(245,158,11,0.10)",
                ))
                fig3.add_hline(
                    y=4.0, line_dash="dot",
                    line_color="rgba(255,255,255,0.25)",
                    annotation_text="Score 4.0",
                    annotation_font_color=MUTED,
                )
                fig3.update_layout(**_layout("Monthly Avg Review Score", 360))
                fig3.update_yaxes(range=[1, 5.5], title="Avg Score")
                st.plotly_chart(fig3, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 6 — GEOGRAPHY & LOGISTICS
# ══════════════════════════════════════════════════════════════════════════════
with TAB_GEO:
    cust_map  = q_customer_order_map(FILTERS)
    sell_map  = q_seller_map(FILTERS)
    region_df = q_regional_performance(FILTERS)

    # ── KPI row ───────────────────────────────────────────────────────────────
    g1, g2, g3, g4 = st.columns(4)
    regions_covered = region_df["region"].nunique() if not region_df.empty else 0
    states_covered  = cust_map["state"].nunique()   if not cust_map.empty  else 0
    cities_covered  = cust_map["city"].nunique()    if not cust_map.empty  else 0

    # Delivery gap: North vs Southeast (worst vs best)
    if not region_df.empty and len(region_df) >= 2:
        max_days = region_df["avg_delivery_days"].max()
        min_days = region_df["avg_delivery_days"].min()
        delivery_gap = max_days - min_days
    else:
        delivery_gap = 0.0

    g1.metric("Regions Covered",    str(regions_covered))
    g2.metric("States with Orders", str(states_covered))
    g3.metric("Cities with Orders", f"{cities_covered:,}")
    g4.metric("Max–Min Delivery Gap", f"{delivery_gap:.1f} days",
              help="Difference in avg delivery days between slowest and fastest region")

    st.markdown("---")

    # ── Demand density heatmap ────────────────────────────────────────────────
    if not cust_map.empty:
        fig_density = px.density_mapbox(
            cust_map, lat="lat", lon="lng", z="orders",
            radius=18,
            hover_data={"city": True, "state": True, "orders": True,
                        "revenue": ":.0f", "lat": False, "lng": False},
            color_continuous_scale=["#0f172a", PAL["blue"], PAL["teal"], "#f0fdf4"],
            labels={"orders": "Orders", "revenue": "Revenue (R$)"},
        )
        fig_density.update_layout(
            mapbox_style="carto-darkmatter",
            mapbox_center={"lat": -14.2, "lon": -51.9},
            mapbox_zoom=3,
            paper_bgcolor=BG,
            margin=dict(l=0, r=0, t=36, b=0),
            height=500,
            title=dict(text="Customer Order Demand Density", font=dict(color=FONT, size=13)),
            coloraxis_colorbar=dict(
                title=dict(text="Orders", font=dict(color=MUTED)),
                tickfont=dict(color=MUTED),
                bgcolor=BG,
            ),
        )
        st.plotly_chart(fig_density, use_container_width=True)

    st.markdown("---")

    # ── Coverage map + Regional performance ───────────────────────────────────
    col_map, col_reg = st.columns([3, 2])

    with col_map:
        fig_cov = go.Figure()
        if not cust_map.empty:
            # Normalise marker size to 4–20px range
            max_orders = cust_map["orders"].max() or 1
            sizes = (cust_map["orders"] / max_orders * 16 + 4).clip(4, 20)
            fig_cov.add_trace(go.Scattermapbox(
                lat=cust_map["lat"], lon=cust_map["lng"],
                mode="markers",
                marker=dict(size=sizes, color=PAL["blue"], opacity=0.55),
                text=cust_map["city"] + ", " + cust_map["state"]
                     + "<br>Orders: " + cust_map["orders"].astype(str),
                hoverinfo="text",
                name="Customers",
            ))
        if not sell_map.empty:
            fig_cov.add_trace(go.Scattermapbox(
                lat=sell_map["lat"], lon=sell_map["lng"],
                mode="markers",
                marker=dict(size=7, color=PAL["amber"], opacity=0.75),
                text=sell_map["city"] + ", " + sell_map["state"]
                     + "<br>Sellers: " + sell_map["seller_count"].astype(str),
                hoverinfo="text",
                name="Sellers",
            ))
        fig_cov.update_layout(
            mapbox_style="carto-darkmatter",
            mapbox_center={"lat": -14.2, "lon": -51.9},
            mapbox_zoom=3,
            paper_bgcolor=BG,
            margin=dict(l=0, r=0, t=36, b=30),
            height=550,
            title=dict(text="Customer Demand vs Seller Supply Coverage",
                       font=dict(color=FONT, size=13)),
            legend=dict(bgcolor=BG, font=dict(color=FONT, size=11),
                        x=0.01, y=0.99),
        )
        st.plotly_chart(fig_cov, use_container_width=True)

    with col_reg:
        if not region_df.empty:
            fig_reg = go.Figure()
            fig_reg.add_trace(go.Bar(
                x=region_df["region"], y=region_df["revenue"],
                name="Revenue (R$)",
                marker_color=PAL["blue"],
                opacity=0.85,
                yaxis="y1",
            ))
            fig_reg.add_trace(go.Scatter(
                x=region_df["region"], y=region_df["avg_delivery_days"],
                name="Avg Delivery Days",
                mode="lines+markers",
                line=dict(color=PAL["amber"], width=2.2),
                marker=dict(size=6),
                yaxis="y2",
            ))
            fig_reg.update_layout(**_layout("Revenue & Delivery Days by Region", 420))
            fig_reg.update_layout(
                yaxis=dict(title="Revenue (R$)", gridcolor=GRID,
                           tickprefix="R$", tickformat=",.0f", tickfont=dict(color=MUTED)),
                yaxis2=dict(title="Avg Delivery Days", overlaying="y", side="right",
                            gridcolor="rgba(0,0,0,0)", tickfont=dict(color=MUTED)),
                barmode="overlay",
                legend=dict(x=0.01, y=0.99, bgcolor=BG),
            )
            st.plotly_chart(fig_reg, use_container_width=True)
