default_environment: dev
project_id: 019cd570-087f-78ed-85d1-032c8d86c26f
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
        - entity: customers
          path: ../data/olist_customers_dataset.csv
          keys: [customer_id]
        - entity: order_items
          path: ../data/olist_order_items_dataset.csv
          keys: [order_item_id, order_id]
        - entity: order_payments
          path: ../data/olist_order_payments_dataset.csv
          keys: [order_id,payment_sequential]
        - entity: order_reviews
          path: ../data/olist_order_reviews_dataset.csv
          keys: [review_id]
        - entity: orders
          path: ../data/olist_orders_dataset.csv
          keys: [order_id]
        - entity: products
          path: ../data/olist_products_dataset.csv
          keys: [product_id]
        - entity: sellers
          path: ../data/olist_sellers_dataset.csv
          keys: [seller_id]
        - entity: geolocation
          path: ../data/olist_geolocation_dataset.csv
          keys: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng]
        - entity: product_category_name_translation
          path: ../data/product_category_name_translation.csv
          keys: [product_category_name]
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<70
    config:
      project: $GCP_PROJECT_ID
      credentials_path: $GCP_CREDENTIALS_PATH
      dataset: raw_olist
      batch_size: 1000
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      location: US
      method: batch_job
